from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('tournament/', views.tournament, name='tournament'),
    # path('tournament/add/', views.add_tournament, name='add_tournament'),
    # path('tournament/update/<str:t>', views.update_tournament, name='update_tournament'),
    # path('tournament/update/', views.update_tournament, name='update_tournament'),
    path('team/detail/', views.team_detail, name='team_detail'),
    path('team/summary/', views.team_summary, name='team_summary'),
    # path('team/update/', views.update_team, name='update_team'),
    # path('session/<str:t>/', views.session, name='session'),
    path('session/detail/', views.session_detail, name='session_detail'),
    path('session/summary/', views.session_summary, name='session_summary'),
    path('matchups/', views.matchups, name='matchups'),
    path('matches/', views.matches, name='matchess'),
    path('matchups/td-assignment', views.matchups_td_assignment, name='matchups_td_assignment'),
    path('td/', views.td, name='td'),
    path('matchups/td/add/', views.add_td, name='add_td'),
    path('faqs/', views.faqs, name='faqs'),
    path('single_tournament_ajax/', views.single_tournament_ajax, name='single_tournament_ajax'),
    path('tournament_ajax/', views.tournament_ajax, name='tournament_ajax'),
    path('tournament_ajax3/', views.tournament_ajax3, name='tournament_ajax3'),
    path('ajaxcall/', views.ajaxcall, name='ajaxcall'),
    path('ajax_sessionsummary/', views.ajax_sessionsummary, name='ajax_sessionsummary'),
    path('ajax_session_new/', views.ajax_session_new, name='ajax_session_new'),
    path('ajaxcall_team_details/', views.ajaxcall_team_details, name='ajaxcall_team_details'),
    path('ajax_teamsummary/', views.ajax_teamsummary, name='ajax_teamsummary'),
    path('ajax_call_new/', views.ajax_call_new, name='ajax_call_new'),
    path('tournament_ajaxajax/', views.tournament_ajaxajax, name='tournament_ajaxajax'),
    path('matchesajaxcall/', views.matchesajaxcall, name='matchesajaxcall'),
    path('newajax_sessionsummary/', views.newajax_sessionsummary, name='newajax_sessionsummary'),
    path('ajax_call_tournament_tomatch/', views.ajax_call_tournament_tomatch, name='ajax_call_tournament_tomatch'),
    path('ajaxcall_td_function/<int:match>/<str:td>/', views.ajaxcall_td_function, name='ajaxcall_td_function')
]

