# Generated by Django 3.2.4 on 2021-06-06 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255, null=True)),
                ('format', models.CharField(max_length=15, null=True)),
                ('scoring', models.CharField(max_length=15, null=True)),
                ('host', models.CharField(max_length=255, null=True)),
                ('num_teams', models.CharField(max_length=255, null=True)),
                ('num_segs', models.CharField(max_length=255, null=True)),
                ('no_invite', models.BooleanField(default=False)),
                ('slow', models.BooleanField(default=False)),
                ('use_predealt', models.BooleanField(default=False)),
                ('barometer', models.BooleanField(default=False)),
                ('allow_kibitzers', models.BooleanField(default=False)),
                ('allow_undos', models.BooleanField(default=False)),
                ('other_hacks', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('bbo_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('host', models.CharField(max_length=255, null=True)),
                ('start_date', models.CharField(max_length=12, null=True)),
                ('end_date', models.CharField(max_length=12, null=True)),
                ('format', models.CharField(choices=[('Knockout', 'Knockout'), ('Mixed', 'Mixed'), ('Round Robin', 'Round Robin'), ('Swiss', 'Swiss')], max_length=15, null=True)),
                ('is_active', models.BooleanField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=100, null=True)),
                ('team_name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField()),
                ('cap_name', models.CharField(max_length=255, null=True)),
                ('cap_email', models.EmailField(max_length=50)),
                ('cap_bbo_id', models.CharField(max_length=255)),
                ('cap_number', models.CharField(max_length=255, null=True)),
                ('cap_country', models.CharField(max_length=255, null=True)),
                ('cap_playing', models.BooleanField()),
                ('player_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='tournamentcreation.teamplayer')),
                ('player_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='tournamentcreation.teamplayer')),
                ('player_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='tournamentcreation.teamplayer')),
                ('player_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to='tournamentcreation.teamplayer')),
                ('player_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_5', to='tournamentcreation.teamplayer')),
                ('player_6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_6', to='tournamentcreation.teamplayer')),
                ('player_7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_7', to='tournamentcreation.teamplayer')),
                ('player_8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_8', to='tournamentcreation.teamplayer')),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournamentcreation.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TD',
            fields=[
                ('bbo_username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('is_global', models.BooleanField()),
                ('tournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Segments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.segment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.tournament'),
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.segment')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.session')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_num', models.IntegerField(null=True, unique=True)),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.session')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tournamentcreation.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tournamentcreation.team')),
            ],
        ),
    ]
