# Generated by Django 3.2.4 on 2021-06-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentcreation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='number_of_boards',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='start_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='segment',
            name='starting_board_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
