# Generated by Django 3.1.13 on 2021-07-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentcreation', '0002_auto_20210606_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='seating',
            name='east',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='east', to='tournamentcreation.teamplayer'),
        ),
        migrations.AddField(
            model_name='seating',
            name='north',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='north', to='tournamentcreation.teamplayer'),
        ),
        migrations.AddField(
            model_name='seating',
            name='south',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='south', to='tournamentcreation.teamplayer'),
        ),
        migrations.AddField(
            model_name='seating',
            name='west',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='west', to='tournamentcreation.teamplayer'),
        ),
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seating',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session_segments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
