# Generated by Django 3.1.13 on 2021-07-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentcreation', '0004_auto_20210720_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='match_id',
        ),
        migrations.AddField(
            model_name='match',
            name='segement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.segment'),
        ),
    ]
