# Generated by Django 3.1.13 on 2021-07-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentcreation', '0005_auto_20210720_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='east',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seating',
            name='north',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seating',
            name='segment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.segment'),
        ),
        migrations.AlterField(
            model_name='seating',
            name='session_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournamentcreation.session'),
        ),
        migrations.AlterField(
            model_name='seating',
            name='south',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seating',
            name='west',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
